spring.application.name=UserAuthSystem
spring.data.mongodb.uri=mongodb+srv://swapnil:swapnil@first.grjbywe.mongodb.net/mydb?appName=UserAuth
spring.data.mongodb.auto-index-creation=true
spring.data.logging=false